# replace "catw-next-2023" in the three targets below with your actual project(s)
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: pop-stats-pipeline-1693267942
description: pop-stats application delivery pipeline
serialPipeline:
 stages:
 - targetId: prod
   profiles:
   - prod
   strategy:
    canary:
      runtimeConfig:
        kubernetes:
          serviceNetworking:
            service: "pop-stats"
            deployment: "pop-stats"
      canaryDeployment:
        percentages: [5]
        verify: true
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod cluster 1
gke:
  cluster: projects/catw-next-2023/locations/us-central1/clusters/prodcluster1